root: true
extends:
    - cos-ember
rules:
    prefer-template: warn
    no-param-reassign: off
    comma-dangle: off
    ember/named-functions-in-promises: off
    ember/local-modules: off
    ember/no-empty-attrs: off
<<<<<<< HEAD
    ember/no-observers: off
    ember/closure-actions: off
=======

>>>>>>> b2ed027... Fix errors and warnings
